<a href="https://colab.research.google.com/github/Namesakenberg/Practical_deep_learning_using_pytorch/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors in Pytorch


Tensors :  **Tensor is a data structure , a way of representing data.**

Tensors are used to represent multi dimensional arrays.
Thus , eveything that an array can do in 1D , tensors can do it in n-D **bold text**

Dimension : The number of directions in which the tensor is spread out in.

0 dimension tensor : spread in no direction i.e a scalar

1 dimension tensor : spread in one direction -> a vectors or array.
eg : embeddings used to make a dense vector from a word.

2 dimension tensor : spread in 2 directions
eg : GreyScale image from MNIST , which only has 2 dimension

3 dimension tensor : spread in 3 dimensions
eg : Colored images , they have 3 channels R,G,B : [128,128,3]

4D tensor : batches of images , passed to an NN while training
[32 , 128 ,128 ,3]

5D tensor : Videos , which is a sequence of images with frames


 ***memory consumed by a tensor is 8 * n bytes*** , where n is number of elements

  
thus a 2x3 tensor will take 48 bytes

*Why are tensors so important in deep learning ?*

1) we can perform basic mathematical operations efficiently


2) we can map the real word data into deep learning using tensors , like text,images,


3) Efficient Computations : we can run them on GPU or TPU and can do parallel processing.
thus operations between huge matrices , vectors is done efficiently , when represented them using tensors

*where are tensors used in deep learning ?*

1) Data Storage : we can store any form of data using tensors , thus images , text , videos are stored easily

**2) the learnable parameters in Neural Nets like weights and bias are in the tensor form**

**3) All the matrix operations and the operations in forward and backpropagation , all the operations are on tensor**

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU",torch.cuda.get_device_properties(0))
else:
  print("NO Gpu , using CPU")

GPU _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15095MB, multi_processor_count=40, uuid=d56808cf-ca63-14cf-3cf4-cffcdc774a2f, pci_bus_id=0, pci_device_id=4, pci_domain_id=0, L2_cache_size=4MB)


## Creating a tensor

In [5]:
t1 = torch.empty(3,3)

# empty function allocates space in the memory , it does not assign value in the memory
# , it shows the existing values there


In [6]:
type(t1)

torch.Tensor

In [11]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(1,2)

# creates tensor with random values

tensor([[0.0568, 0.9885]])

In [12]:
# set seed for reproducibility

torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [13]:
torch.tensor([[10,20,30] , [70,80,90]])

tensor([[10, 20, 30],
        [70, 80, 90]])

In [14]:
torch.arange(0,10,2)

# numbers in range 0 to 10 with steps = 2

tensor([0, 2, 4, 6, 8])

In [16]:
torch.linspace(0,14,10)

# 10 evenly spaced values between 0 to 14

tensor([ 0.0000,  1.5556,  3.1111,  4.6667,  6.2222,  7.7778,  9.3333, 10.8889,
        12.4444, 14.0000])

In [17]:
torch.eye(3)

# identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# tensor Shapes

In [20]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [22]:
torch.empty_like(x)

# make an empty tensor with the same shape of the tensor passed


tensor([[7589742065960902512, 3202179600393397613,  723435908101054474],
        [6872330769136574218, 7308339945077226784, 2910562809998701352]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
torch.rand_like(x , dtype = torch.float64)

tensor([[0.5504, 0.9424, 0.3835],
        [0.6327, 0.5669, 0.3390]], dtype=torch.float64)

# Tensor data types

In [30]:
x.dtype

torch.int64

In [31]:
# specify data type while creating the tensor
torch.tensor([1.0,2.0,3.0] , dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [36]:
# convert
print(x.dtype)

x.to(torch.float64)

torch.int64


tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Math operations on tensors

## Scalar operations

In [40]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [48]:
x+2

tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]])

In [43]:
x-2

tensor([[-1,  0,  1,  2],
        [ 3,  4,  5,  6]])

In [44]:
x*2

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])

In [45]:
x//2

tensor([[0, 1, 1, 2],
        [2, 3, 3, 4]])

In [46]:
x**2

tensor([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])

In [47]:
x%2

tensor([[1, 0, 1, 0],
        [1, 0, 1, 0]])

## element wise operations


In [53]:
a = torch.tensor([[1,2,3,4],[5,6,7,8]])
b = torch.tensor([[5,6,7,8],[9,10,11,12]])

print(a)
print(b)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [54]:
print(a+b)

tensor([[ 6,  8, 10, 12],
        [14, 16, 18, 20]])


In [56]:
print(a-b)

tensor([[-4, -4, -4, -4],
        [-4, -4, -4, -4]])


In [57]:
print(a*b)

tensor([[ 5, 12, 21, 32],
        [45, 60, 77, 96]])


In [58]:
print(a/b)

tensor([[0.2000, 0.3333, 0.4286, 0.5000],
        [0.5556, 0.6000, 0.6364, 0.6667]])


In [60]:
c = torch.tensor([1.2,2.3,4.5,5.6,6.7])
c

tensor([1.2000, 2.3000, 4.5000, 5.6000, 6.7000])

In [61]:
torch.ceil(c)

tensor([2., 3., 5., 6., 7.])

In [62]:
torch.floor(c)

tensor([1., 2., 4., 5., 6.])

In [66]:
torch.clamp(c,min=2,max=4)

tensor([2.0000, 2.3000, 4.0000, 4.0000, 4.0000])

 ## reduction operations

In [78]:
m = torch.randint(size = (2,3) , low = 0, high = 10)
m

tensor([[4, 5, 4],
        [0, 8, 9]])

In [80]:
# sum
print("sum " , torch.sum(m))

print("element wise row sum" , torch.sum(m , dim=0))

print("mean of the tensor",torch.mean(m , dtype=torch.float64))

print("median" , torch.median(m))

print("max",torch.max(m))

print("min",torch.min(m))

print("pos of min element",torch.argmin(m))

print("pos of max element",torch.argmax(m))

sum  tensor(30)
element wise row sum tensor([ 4, 13, 13])
mean of the tensor tensor(5., dtype=torch.float64)
median tensor(4)
max tensor(9)
min tensor(0)
pos of min element tensor(3)
pos of max element tensor(5)


## Matrix operations

In [94]:
matrix1 = torch.randint(low = 0 , high = 10 , size = (2,3))
matrix2 = torch.randint(low = 0 , high = 10 , size = (3,2))

print(matrix1)
print(matrix2)

tensor([[8, 3, 1],
        [8, 2, 6]])
tensor([[1, 4],
        [9, 1],
        [8, 9]])


In [101]:
torch.transpose(matrix1,0,1)

tensor([[8, 8],
        [3, 2],
        [1, 6]])

In [86]:
torch.matmul(matrix1 , matrix2)

tensor([[ 30,  25],
        [117, 107]])

# Inplace operations

In [102]:
m = torch.randint(0,10,(2,3))
n = torch.randint(0,10,(2,3))

print(m)
print(n)

tensor([[7, 4, 9],
        [6, 4, 4]])
tensor([[6, 6, 5],
        [6, 3, 6]])


In [103]:
m+n

# this result is a new tensor

tensor([[13, 10, 14],
        [12,  7, 10]])

In [104]:
# inplce operations

m.add_(n)

tensor([[13, 10, 14],
        [12,  7, 10]])

In [105]:
m

tensor([[13, 10, 14],
        [12,  7, 10]])

In [106]:
m.relu_()

# inplace operations will have _ after the function call

tensor([[13, 10, 14],
        [12,  7, 10]])

# Copy a tensor

In [137]:
a = torch.rand(2,3)
a

tensor([[0.3810, 0.4269, 0.1977],
        [0.1699, 0.6641, 0.9510]])

In [138]:
b = a

In [139]:
b

tensor([[0.3810, 0.4269, 0.1977],
        [0.1699, 0.6641, 0.9510]])

In [140]:
a[0][0]=0

In [141]:
a

tensor([[0.0000, 0.4269, 0.1977],
        [0.1699, 0.6641, 0.9510]])

In [142]:
b

tensor([[0.0000, 0.4269, 0.1977],
        [0.1699, 0.6641, 0.9510]])

In [ ]:
# thus even if a copy is created and then changes are made into the original term ,the changes will still be seen in the copy

In [143]:
# thus to avoid this

c = a.clone()

# now a permanant copy of a particular instance of A is created , now even if changes are made in a , they cannot be see in c